
const actionTypes = {
    CLOSE_ERROR_ALERT: 'CLOSE_ERROR_ALERT',
    LOGIN_PROGRESS : 'LOGIN_PROGRESS',
    LOGIN_SUCCEED : 'LOGIN_SUCCEED',
    SIGNUP_PROGRESS : 'SIGNUP_PROGRESS',
    SIGNUP_SUCCEED : 'SIGNUP_SUCCEED',
    LOGOUT_SUCCEED : 'LOGOUT_SUCCEED',
    LOGIN_ERROR: 'LOGIN_ERROR',
    SIGNUP_ERROR : 'SIGNUP_ERROR',
    SIGNUP_ERROR_ALERT : 'SIGNUP_ERROR_ALERT',
    LOGIN_ERROR_ALERT : 'LOGIN_ERROR_ALERT',
    LOAD_LOCATION: 'LOAD_LOCATION'
}
export default actionTypes;